name: Daily Scrape

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      run: python scraper.py

    - name: Run Emailer
      run: python emailer.py
      env:
        EMAIL: ${{ secrets.EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    - name: Commit & Push Updated Files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add karkidi_jobs.csv kmeans_model.pkl tfidf_vectorizer.pkl
        git commit -m "Daily update of job listings" || echo "No changes to commit"
        git push
